############## clock define##################
create_clock -period 5.000 -name sys_clk [get_ports clk_200m_in_p]
set_property PACKAGE_PIN AR32 [get_ports clk_200m_in_p]
set_property PACKAGE_PIN AT32 [get_ports clk_200m_in_n]
set_property IOSTANDARD DIFF_SSTL12 [get_ports clk_200m_in_n]

set_property PACKAGE_PIN A8 [get_ports nrst]
set_property IOSTANDARD LVCMOS33 [get_ports nrst]


#set_property -dict {PACKAGE_PIN AL15 IOSTANDARD LVCMOS18} [get_ports sclk]
#set_property -dict {PACKAGE_PIN AV13 IOSTANDARD LVCMOS18} [get_ports csb ]
#set_property -dict {PACKAGE_PIN AV12 IOSTANDARD LVCMOS18} [get_ports mosi]
#set_property -dict {PACKAGE_PIN AR14 IOSTANDARD LVCMOS18} [get_ports miso]

set_property -dict {PACKAGE_PIN AL15   IOSTANDARD LVCMOS18} [get_ports tx_clk       ]
set_property -dict {PACKAGE_PIN AV13   IOSTANDARD LVCMOS18} [get_ports tx_data_i[0 ]]
set_property -dict {PACKAGE_PIN AV12   IOSTANDARD LVCMOS18} [get_ports tx_data_i[1 ]]
set_property -dict {PACKAGE_PIN AR14   IOSTANDARD LVCMOS18} [get_ports tx_data_i[2 ]]
set_property -dict {PACKAGE_PIN AT14   IOSTANDARD LVCMOS18} [get_ports tx_data_i[3 ]]
set_property -dict {PACKAGE_PIN AV16   IOSTANDARD LVCMOS18} [get_ports tx_data_i[4 ]]
set_property -dict {PACKAGE_PIN AW16   IOSTANDARD LVCMOS18} [get_ports tx_data_i[5 ]]
set_property -dict {PACKAGE_PIN AL22   IOSTANDARD LVCMOS18} [get_ports tx_data_i[6 ]]
set_property -dict {PACKAGE_PIN AM22   IOSTANDARD LVCMOS18} [get_ports tx_data_i[7 ]]
set_property -dict {PACKAGE_PIN AT17   IOSTANDARD LVCMOS18} [get_ports tx_data_i[8 ]]
set_property -dict {PACKAGE_PIN AU17   IOSTANDARD LVCMOS18} [get_ports tx_data_i[9 ]]
set_property -dict {PACKAGE_PIN AJ20   IOSTANDARD LVCMOS18} [get_ports tx_data_i[10]]
set_property -dict {PACKAGE_PIN AJ19   IOSTANDARD LVCMOS18} [get_ports tx_data_i[11]]
set_property -dict {PACKAGE_PIN AR18   IOSTANDARD LVCMOS18} [get_ports tx_data_i[12]]
set_property -dict {PACKAGE_PIN AU22   IOSTANDARD LVCMOS18} [get_ports tx_data_q[0 ]]
set_property -dict {PACKAGE_PIN AH21   IOSTANDARD LVCMOS18} [get_ports tx_data_q[1 ]]
set_property -dict {PACKAGE_PIN AJ16   IOSTANDARD LVCMOS18} [get_ports tx_data_q[2 ]]
set_property -dict {PACKAGE_PIN AJ15   IOSTANDARD LVCMOS18} [get_ports tx_data_q[3 ]]
set_property -dict {PACKAGE_PIN AT12   IOSTANDARD LVCMOS18} [get_ports tx_data_q[4 ]]
set_property -dict {PACKAGE_PIN AT11   IOSTANDARD LVCMOS18} [get_ports tx_data_q[5 ]]
set_property -dict {PACKAGE_PIN AP16   IOSTANDARD LVCMOS18} [get_ports tx_data_q[6 ]]
set_property -dict {PACKAGE_PIN AR16   IOSTANDARD LVCMOS18} [get_ports tx_data_q[7 ]]
set_property -dict {PACKAGE_PIN AK21   IOSTANDARD LVCMOS18} [get_ports tx_data_q[8 ]]
set_property -dict {PACKAGE_PIN AL21   IOSTANDARD LVCMOS18} [get_ports tx_data_q[9 ]]
set_property -dict {PACKAGE_PIN AN21   IOSTANDARD LVCMOS18} [get_ports tx_data_q[10]]
set_property -dict {PACKAGE_PIN AN20   IOSTANDARD LVCMOS18} [get_ports tx_data_q[11]]
set_property -dict {PACKAGE_PIN AV18   IOSTANDARD LVCMOS18} [get_ports tx_data_q[12]]

set_property C_CLK_INPUT_FREQ_HZ 600000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]